### ISSUE TITLE
Self hosting

### ISSUE THREAD

**Issue by heyfolk** [crizmo/Elina-dev#1]
If we can self host can you please add a env-example file it will help us;)

**Comment by crizmo** [comment]
For hosting locally just make a .env file and have the following stuff in the env 
- token 
- mongoDB srv
- guildID
- owner ID
- prefix

For hosting on a server add the above stuff in the security env area

**Comment by heyfolk** [comment]
Name is sensitive did i have to put same name you mentioned above?

**Comment by crizmo** [comment]
DISCORD_TOKEN - for token
PREFIX - for prefix
ownerID - for id of the bot owner
MONGODB_SRV - for mongo db srv
GUILD_ID - for slash commands (  put the id of the server u want as the dev server )

I will explain the .env structure in the readMD
so this wont be a confusion later on

**Comment by heyfolk** [comment]
Getting this error
![Screenshot_20220219-155109_Brave](https://user-images.githubusercontent.com/60790859/154796912-55b59086-4ccc-4c66-a5c0-ed5f00c6a1b4.png)

**Comment by crizmo** [comment]
your node version is it v16+

**Comment by heyfolk** [comment]
Node v is 16.13.2

**Comment by SiebeBaree** [comment]
@fardeen619 
Version of node doesn't matter. Node-fetch v3 is a ESM-only module. to use require() you need to install node fetch v2.
`npm install node-fetch@2`

**Comment by crizmo** [comment]
It shouldn't matter for the error at hand but the db and some packages need the right node version

**Comment by heyfolk** [comment]
> @fardeen619 Version of node doesn't matter. Node-fetch v3 is a ESM-only module. to use require() you need to install node fetch v2. `npm install node-fetch@2`

Installed still error comes

**Comment by heyfolk** [comment]
Now getting new Error take a look 
![Screenshot_20220221-135133_Brave](https://user-images.githubusercontent.com/60790859/154915698-7eda390e-77eb-49bc-8422-8ae1db6db7d0.png)

**Comment by crizmo** [comment]
I highly recommend you to learn the language , database first then move on making bots
copying the repo as it is will land you in many issues cause the economy and other codes are not stable 

i made the repo public for ppl to help them understand how the codes works and its structure + specific codes
if you want to copy as it is you will have to clone or download it which will make ur repo different from the one i update daily for bug fixes etc.
